{
  bikes(where: {near: {lon: -122.396445, lat: 37.793250, radius: 100}}) {
    bike_id
    feed {
      system_information {
        name
        email
        feed_contact_email
        language
        license_url
        operator
        phone_number
        privacy_last_updated
        privacy_url
        purchase_url
        short_name
        start_date
        system_id
        terms_last_updated
        terms_url
        timezone
        url
        brand_assets {
          brand_image_url
          brand_image_url_dark
          brand_last_modified
          brand_terms_url
          color
        }
      }
      station_information {
        address
        capacity
        contact_phone
        cross_street
        is_charging_station
        is_valet_station
        is_virtual_station
        lat
        lon
        name
        parking_hoop
        parking_type
        post_code
        rental_methods
        short_name
        station_area
        station_id
        region {
          name
          region_id
        }
        status {
          is_installed
          is_renting
          is_returning
          last_reported
          num_bikes_available
          num_bikes_disabled
          num_docks_available
          num_docks_disabled
          station_id
          vehicle_docks_available {
            count
            vehicle_type_ids
          }
          vehicle_types_available {
            count
            num_bikes_disabled
            num_docks_available
            vehicle_type_id
          }
        }
      }
    }
    available_until
    current_fuel_percent
    current_range_meters
    is_disabled
    is_reserved
    last_reported
    lat
    lon
    vehicle_equipment
    pricing_plan {
      currency
      description
      is_taxable
      name
      plan_id
      price
      surge_pricing
      url
      per_km_pricing {
        end
        interval
        rate
        start
      }
      per_min_pricing {
        end
        interval
        rate
        start
      }
    }
    vehicle_type {
      cargo_load_capacity
      cargo_volume_capacity
      color
    }
    station {
      address
      capacity
      contact_phone
    }
  }
}
