# Generated by ariadne-codegen
# Source: ../schema/

from enum import Enum


class DurationUnit(str, Enum):
    SECONDS = "SECONDS"


class DistanceUnit(str, Enum):
    KILOMETERS = "KILOMETERS"
    MILES = "MILES"


class StepMode(str, Enum):
    WALK = "WALK"
    AUTO = "AUTO"
    BICYCLE = "BICYCLE"
    TRANSIT = "TRANSIT"
    LINE = "LINE"


class RelativeDate(str, Enum):
    TODAY = "TODAY"
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"
    NEXT_MONDAY = "NEXT_MONDAY"
    NEXT_TUESDAY = "NEXT_TUESDAY"
    NEXT_WEDNESDAY = "NEXT_WEDNESDAY"
    NEXT_THURSDAY = "NEXT_THURSDAY"
    NEXT_FRIDAY = "NEXT_FRIDAY"
    NEXT_SATURDAY = "NEXT_SATURDAY"
    NEXT_SUNDAY = "NEXT_SUNDAY"


class PlaceAggregationLevel(str, Enum):
    ADM0 = "ADM0"
    ADM0_ADM1 = "ADM0_ADM1"
    ADM0_ADM1_CITY = "ADM0_ADM1_CITY"
    ADM0_CITY = "ADM0_CITY"
    ADM1_CITY = "ADM1_CITY"
    CITY = "CITY"


class ScheduleRelationship(str, Enum):
    SCHEDULED = "SCHEDULED"
    ADDED = "ADDED"
    UNSCHEDULED = "UNSCHEDULED"
    CANCELED = "CANCELED"
    STATIC = "STATIC"
    SKIPPED = "SKIPPED"
    NO_DATA = "NO_DATA"
    REPLACEMENT = "REPLACEMENT"
    DUPLICATED = "DUPLICATED"
    DELETED = "DELETED"


class ImportStatus(str, Enum):
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    IN_PROGRESS = "IN_PROGRESS"


class LicenseValue(str, Enum):
    YES = "YES"
    NO = "NO"
    EXCLUDE_NO = "EXCLUDE_NO"
    UNKNOWN = "UNKNOWN"


class FeedSourceUrlTypes(str, Enum):
    static_current = "static_current"
    static_historic = "static_historic"
    static_planned = "static_planned"
    static_hypothetical = "static_hypothetical"
    realtime_vehicle_positions = "realtime_vehicle_positions"
    realtime_trip_updates = "realtime_trip_updates"
    realtime_alerts = "realtime_alerts"
    gbfs_auto_discovery = "gbfs_auto_discovery"
    mds_provider = "mds_provider"


class FeedSpecTypes(str, Enum):
    GTFS = "GTFS"
    GTFS_RT = "GTFS_RT"
    GBFS = "GBFS"
    MDS = "MDS"
