# Generated by ariadne-codegen
# Source: ../server/rest/feed_request.gql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import FeedSpecTypes


class GetFeeds(BaseModel):
    feeds: List["GetFeedsFeeds"]


class GetFeedsFeeds(BaseModel):
    id: int
    spec: Optional[FeedSpecTypes]
    name: Optional[str]
    onestop_id: str
    languages: Optional[List[str]]
    urls: Optional["GetFeedsFeedsUrls"]
    license: Optional["GetFeedsFeedsLicense"]
    authorization: Optional["GetFeedsFeedsAuthorization"]
    feed_state: Optional["GetFeedsFeedsFeedState"]
    feed_versions: List["GetFeedsFeedsFeedVersions"]


class GetFeedsFeedsUrls(BaseModel):
    static_current: str
    static_historic: List[str]
    static_planned: str
    realtime_vehicle_positions: str
    realtime_trip_updates: str
    realtime_alerts: str
    gbfs_auto_discovery: str
    mds_provider: str


class GetFeedsFeedsLicense(BaseModel):
    spdx_identifier: str
    url: str
    use_without_attribution: str
    create_derived_product: str
    redistribution_allowed: str
    commercial_use_allowed: str
    share_alike_optional: str
    attribution_text: str
    attribution_instructions: str


class GetFeedsFeedsAuthorization(BaseModel):
    type: str
    param_name: str
    info_url: str


class GetFeedsFeedsFeedState(BaseModel):
    feed_version: Optional["GetFeedsFeedsFeedStateFeedVersion"]


class GetFeedsFeedsFeedStateFeedVersion(BaseModel):
    id: int
    sha_1: str = Field(alias="sha1")
    url: str
    fetched_at: Any
    geometry: Optional[Any]
    feed_version_gtfs_import: Optional[
        "GetFeedsFeedsFeedStateFeedVersionFeedVersionGtfsImport"
    ]


class GetFeedsFeedsFeedStateFeedVersionFeedVersionGtfsImport(BaseModel):
    id: int
    in_progress: bool
    success: bool
    exception_log: str


class GetFeedsFeedsFeedVersions(BaseModel):
    id: int
    sha_1: str = Field(alias="sha1")
    fetched_at: Any
    url: str
    earliest_calendar_date: Any
    latest_calendar_date: Any


GetFeeds.model_rebuild()
GetFeedsFeeds.model_rebuild()
GetFeedsFeedsFeedState.model_rebuild()
GetFeedsFeedsFeedStateFeedVersion.model_rebuild()
