query($limit: Int, $ids: [Int!], $after: Cursor, $where: AgencyFilter) {
  agencies(limit: $limit, after: $after, ids: $ids, where: $where) {
    id
    agency_name
    agency_id
    onestop_id
    agency_url
    agency_timezone
    agency_lang
    agency_phone
    agency_fare_url
    agency_email
    geometry
    cursor
    operator {
      onestop_id
      name
      short_name
      tags
      feeds {
        id
        onestop_id
        name
        spec
      }
    }
    places(where: { min_rank: 0.2 }) {
      city_name
      adm0_name
      adm1_name
    }
    feed_version {
      id
      sha1
      fetched_at
      feed {
        id
        onestop_id
      }
    }
    routes(limit: 1000) {
      id
      route_id
      route_short_name
      route_long_name
    }
  }
}
