name: Test Suite

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PGDATABASE: tlv2_test_server
      PGHOST: postgres
      PGPORT: 5432
      TL_TEST_SERVER_DATABASE_URL: postgres://root:for_testing@$postgres:5432/tlv2_test_server?sslmode=disable
      TL_REDIS_URL: ""
      AWS_PROFILE: something
      AWS_REGION: us-east-1
    services:
      postgres:
        image: postgis/postgis:12-3.2-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: for_testing
          POSTGRES_DB: tlv2_test_server
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # redis:
      #   image: redis:6.0.8
      #   ports:
      #     - 6379:6379
      #   # Set health checks to wait until redis has started
      #   options: >-
      #     --health-cmd "redis-cli ping"
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.6'
      - run: |
          git clone https://github.com/interline-io/transitland-lib.git
      - run: ./transitland-lib/internal/schema/postgres/bootstrap.sh
      - run: ./test_setup.sh
      - run: go test -v -count=1 ./...

